### ISSUE TITLE
Buying numbers from the Vonage CLI

### ISSUE THREAD

**Issue by ppinto-vonage** [Vonage/vonage-cli#51]
When trying to buy numbers from a country where there is number availability, like for example the UK (country code GB), the CLI lists numbers.

However, if we try to buy numbers from countries where there are restrictions or there is no availability, let's say Germany (DE), the CLI explodes:
**vonage numbers:search DE**

_TypeError: Cannot read properties of undefined (reading 'map')
    at Table.display (/usr/local/lib/node_modules/@vonage/cli/node_modules/cli-ux/lib/styled/table.js:48:30)
    at Object.table (/usr/local/lib/node_modules/@vonage/cli/node_modules/cli-ux/lib/styled/table.js:280:39)
    at NumberSearch.<anonymous> (/usr/local/lib/node_modules/@vonage/cli/node_modules/@vonage/cli-plugin-numbers/dist/commands/numbers/search.js:13:30)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@vonage/cli/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    TypeError: Cannot read properties of undefined (reading 'map')_

**Comment by kellyjandrews** [comment]
Thanks -  Could you also report this in Jira under "DEVX" and assign it to me - I can tag it appropriately. Thanks!
